<a href="https://colab.research.google.com/github/Matheus-Pombeiro/dataviz_table_styling/blob/main/table_styling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Coleta e preparação de dados

In [1]:
!pip install pandas==2.0.0

Collecting pandas==2.0.0
  Downloading pandas-2.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas==2.0.0) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas==2.0.0) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas==2.0.0) (2024.2)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas==2.0.0) (1.26.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas==2.0.0) (1.16.0)
Downloading pandas-2.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 43.6 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.0.0 which is incompatible.
mizani 0.13.0 requires pandas>=2.2.0, but you have pandas 2.0.0 which is incompatible.
plotnine 0.14.3 requires pandas>=2.2.0, but you have pandas 2.0.0 which is incompatible.
xarray 2024.10.0 requires pandas>=2.1, but you have pandas 2.0.0 which is incompatible.
Successfully installed pandas-2.0.0

In [2]:
# Importando bibliotecas
import pandas as pd

# Obtendo a url dos dados
url = 'https://raw.githubusercontent.com/Matheus-Pombeiro/dataviz_table_styling/refs/heads/main/relatorio_vendas.csv'

# Lendo os dados
df = pd.read_csv(url)
df

,data_pedido,modo_envio,nome_cliente,segmento_cliente,cidade,estado,regiao,departamento,tipo_produto,vendas,quantidade,lucro
0,2018-11-09,Econômica,Thiago Silveira,B2C,Ribeirão Preto,São Paulo,Sudeste,Materiais de construção,encanamentos,890.66,2,142.51
1,2018-11-09,Econômica,Thiago Silveira,B2C,Ribeirão Preto,São Paulo,Sudeste,Materiais de construção,ferramentas,2488.60,3,746.58
2,2018-06-13,Econômica,Giovanna Lima,B2B,Rio de Janeiro,Rio de Janeiro,Sudeste,Jardinagem e paisagismo,sementes,49.71,2,23.36
3,2017-10-12,Entrega padrão,Ana Júlia da Cruz,B2C,Foz do Iguaçu,Paraná,Sul,Materiais de construção,materiais de revestimento,3255.76,5,-1302.31
4,2017-10-12,Entrega padrão,Ana Júlia da Cruz,B2C,Foz do Iguaçu,Paraná,Sul,Jardinagem e paisagismo,vasos,76.05,2,8.56
...,...,...,...,...,...,...,...,...,...,...,...,...
8935,2018-09-30,Entrega padrão,Enrique Santos,B2C,Rio de Janeiro,Rio de Janeiro,Sudeste,Automotivo,ferramentas automotivas,123.22,1,51.75
8936,2019-11-18,Entrega padrão,Heitor Silveira,B2B,Jequié,Bahia,Nordeste,Automotivo,ferramentas automotivas,271.97,1,97.91
8937,2019-11-18,Entrega padrão,Heitor Silveira,B2B,Jequié,Bahia,Nordeste,Automotivo,pneus,700.74,5,189.20
8938,2016-01-22,Econômica,Isabel Araújo,B2C,João Pessoa,Paraíba,Nordeste,Materiais de construção,iluminação,85.84,3,13.95
8939,2019-05-05,Econômica,Esther Rodrigues,B2C,Mossoró,Rio Grande do Norte,Nordeste,Jardinagem e paisagismo,mobiliário de exterior,826.74,2,248.02

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   data_pedido       8940 non-null   object
 1   modo_envio        8940 non-null   object
 2   nome_cliente      8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   cidade            8940 non-null   object
 5   estado            8940 non-null   object
 6   regiao            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_produto      8940 non-null   object
 9   vendas            8940 non-null   float64
 10  quantidade        8940 non-null   int64
 11  lucro             8940 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 838.2+ KB

In [4]:
df['data_pedido'] = pd.to_datetime(df['data_pedido'])

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   data_pedido       8940 non-null   datetime64[ns]
 1   modo_envio        8940 non-null   object
 2   nome_cliente      8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   cidade            8940 non-null   object
 5   estado            8940 non-null   object
 6   regiao            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_produto      8940 non-null   object
 9   vendas            8940 non-null   float64
 10  quantidade        8940 non-null   int64
 11  lucro             8940 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 838.2+ KB

# Missão 1: Time de vendas

Precisamos construir uma visualização para indicar os **10 maiores clientes por total de venda**.

Com isso, a equipe de vendas pode pensar em estratégias para manter esses clientes comprando em nossa loja.

In [6]:
df_clientes_vendas = df.groupby('nome_cliente')[['vendas']].sum().nlargest(10, 'vendas').copy()
df_clientes_vendas = df_clientes_vendas.reset_index()
df_clientes_vendas

            nome_cliente    vendas
0    Maria Luiza Almeida  64777.54
1        Ana Julia Pinto  51398.95
2            Ryan Farias  48178.94
3         Heitor da Mata  47610.85
4  Maria Clara Gonçalves  46946.42
5         Raquel Freitas  44826.26
6             Davi Ramos  43769.21
7            Amanda Melo  42354.27
8         Alexia Ribeiro  41238.84
9         Calebe Ribeiro  41056.70

In [7]:
df_clientes_vendas.columns = ['Clientes', 'Vendas']
df_clientes_vendas['Rank'] = df_clientes_vendas.index + 1
df_clientes_vendas.set_index('Rank', inplace=True)
df_clientes_vendas

                   Clientes    Vendas
Rank
1       Maria Luiza Almeida  64777.54
2           Ana Julia Pinto  51398.95
3               Ryan Farias  48178.94
4            Heitor da Mata  47610.85
5     Maria Clara Gonçalves  46946.42
6            Raquel Freitas  44826.26
7                Davi Ramos  43769.21
8               Amanda Melo  42354.27
9            Alexia Ribeiro  41238.84
10           Calebe Ribeiro  41056.70

In [8]:
s = df_clientes_vendas.style
s

In [9]:
s.format({'Vendas': 'R$ {:,.2f}'})
s

## Aula 1 - desafio

In [10]:
url = 'https://raw.githubusercontent.com/Matheus-Pombeiro/dataviz_table_styling/refs/heads/main/loja_livro_filmes.csv'
df_loja = pd.read_csv(url)
df_loja.head(2)

,pais,id_cliente,data_pedido,data_chegada,tipo_compra,numero_pedido,tamanho_pacote,unidades,custo_empacotamento,custo_envio,tipo_desconto,categoria,tipo_consumo,tipo_cliente,custo_produto
0,Argentina,111962928,2002-02-15,2002-03-10,Normal,98091426,Pacote pequeno,1,3.0,5.99,Sem desconto,BlueRay,Alto Consumo,B2C,8.99
1,Argentina,145148150,2004-11-05,2004-11-26,Normal,98087803,Pacote pequeno,3,1.0,6.99,Sem desconto,BlueRay,Alto Consumo,B2C,7.99

In [11]:
df_loja_paises = df_loja.groupby('pais')[['unidades']].sum().nlargest(9, 'unidades').copy()
df_loja_paises = df_loja_paises.reset_index()

In [12]:
df_loja_paises.columns = ['País', 'Unidades Pedidas']
df_loja_paises['Rank'] = df_loja_paises.index + 1
df_loja_paises.set_index('Rank', inplace=True)
df_loja_paises

           País  Unidades Pedidas
Rank
1     Argentina              5591
2       Equador              5566
3      Paraguai              5564
4          Peru              5550
5     Venezuela              5529
6      Colômbia              5504
7        Brasil              5473
8       Uruguai              5377
9         Chile              5304

In [13]:
s_loja = df_loja_paises.style
s_loja.format({'Unidades Pedidas': '{} prod'})
s_loja

# Missão 2: Time comercial

Precisamos construir uma visualização que permita associar o **total ganho em vendas e o total lucrado por tipo de produto**.

Isso vai permitir que o time comercial possa focar em estratégias para alavancar as rendas que ganham com cada tipo de produto vendido na loja.

In [14]:
df_venda_lucro = df.groupby('tipo_produto')[['vendas', 'lucro']].sum()
df_venda_lucro.index.name = 'tipo produto'
df_venda_lucro

                               vendas      lucro
tipo produto
decoração de jardim          82680.87   19880.86
encanamentos                373224.39  -11243.39
equipamentos de limpeza     542304.55   17448.30
ferramentas                 995159.43   82042.91
ferramentas automotivas     502109.33  126660.54
ferramentas de jardinagem   648880.47  106408.80
fertilizantes                53144.55   22509.86
iluminação                  275229.82   40531.09
materiais de paisagismo     150552.80   -3823.67
materiais de revestimento   629656.41  -57737.23
mobiliário de exterior      328932.37   53569.57
mudas                         8811.69    2762.88
pesticidas                  244958.41  106688.03
peças de reposição          486907.88  182297.32
pneus                      1022430.50  134923.09
sementes                     39980.49   17730.06
vasos                       696045.39   67887.28

In [15]:
estilo_produto = df_venda_lucro.style
estilo_produto

In [18]:
estilo_produto.format('R$ {:,.2f}')\
              .highlight_max(color='lightgreen')\
              .highlight_min(color='red')
estilo_produto

In [19]:
estilo_produto.format('R$ {:,.2f}').background_gradient(cmap='Greens')
estilo_produto

In [22]:
cabecalho = {
    'selector': 'th',
    'props': 'font-weight: bold; font-family: Arial; text-align: center; text-transform: capitalize'
}

estilo_produto.set_table_styles([cabecalho], overwrite=False)

## Aula 2 - desafio

In [23]:
df_produto_custo = df_loja.groupby('categoria')[['custo_produto']].sum()
df_produto_custo.index.name = 'Categoria produto'
df_produto_custo.columns = ['Custo de pedidos']
df_produto_custo

                   Custo de pedidos
Categoria produto
BlueRay                    14191.36
CD                         10514.28
Coleção                    73128.59
Livro                      78213.80

In [24]:
s_produto = df_produto_custo.style
s_produto.format('R$ {:,.2f}')\
          .highlight_max(color='red')\
          .highlight_min(color='lightgreen')
s_produto

# Missão 3: Time de logística

Precisamos construir uma visualização que permita entender a **distribuição de pedidos por região do Brasil**.

Isso vai permitir que o time logística entenda onde é mais interessante focar material e pessoas.

# Missão 4: Time de logística

Novamente o time de logística deseja repensar sua estrutura e organização de fornecimento de produtos e para isso, foi pensada em uma visualização que permita identificar padrão de **quantidade de produtos solicitados por mês por departamento**.

# Missão 5: Relatório de performance

O relatório de performance é um documento muito importante para a empresa. Nele, todos que trabalham na loja podem entender como anda a empresa. Por conta disso, tabelas bem construídas são essenciais para mostrar os dados da melhor forma.

Portanto, precisamos construir uma visualização que permita entender a **relação entre tipos de clientes e modo de envio de produtos de acordo com as vendas**. Com isso, será possível destacar no relatório qual o modo de envio e quais tipos de modo de envio mais geraram ganho em vendas.